#+title: Sk4rd's Wallpapers
#+options: toc:nil num:nil

This is my wallpaper repository, featuring lots of different themes
and art styles. You can find all of the wallpapers in 4K
(3840x2160). I have also provided a shell script, which enables you to
resize the images to your preferred resolution.

* Wallpapers
Below are links to the directories containing my wallpapers,
categorized by theme.

+ [[file:voxel/][Voxel]]
+ [[file:steampunk/][Steampunk]]
+ [[file:fractals/][Fractals]]  
+ [[file:pom-pom-purin/][Sanrio - Pom Pom Purin]]
+ [[file:kuromi/][Sanrio - Kuromi]]    

* Resize script
Before you can resize the images, you need to have =imagemagick=
installed on your system.

#+begin_src shell :results output :exports both
  ./resize.sh -h
#+end_src

#+NAME: Result of -h
#+RESULTS:
: Usage: resize.sh [-h] [-i INPUT] [-o OUTPUT] [-r RESOLUTIONS]
: Resize images to multiple resolutions.
: 
:     -h              display this help and exit
:     -i INPUT        input image. (Required)
:     -o OUTPUT       output directory. Defaults to current directory.
:     -r RESOLUTIONS  comma separated list of resolutions (e.g. "800x600,1024x768"). (Required)
: 
: Example: resize.sh -i image.jpg -o resized/ -r "800x600,1024x768"

** Dependencies
+ =imagemagick=

* Nix
Since I daily drive [[https://nixos.org/][NixOS]] and want to have a clean config, I have
written a flake in which I define a home-manager module for my
wallpaper repo. This module can be used in any home-manager
configuration as such:

#+begin_src nix
  {
    description = "Example NixOS Flake";

    # inputs.nixpkgs...
    # inputs.home-manager...
  
    # Specify this repository as an input for your flake
    inputs.wallpapers.url = "github:sk4rd/wallpapers";

    # Then you can pass it to a home-manager configuration
    outputs = { self, wallpapers, ... }@inputs: {
      # ...
      homeConfiguration."user@hostname" =
        home-manager.lib.homeManagerConfiguration {
          modules = [
            # Pass the wallpaper-module to your home-manager config
            inputs.wallpapers.homeManagerModules.wallpaper-module
          ];
        }
      # ...
    };
  }
#+end_src

** Configuration options
You can then use the wallpaper module in any nix file under
home-manager. You can specify which wallpaper theme you want to use,
or change the default path, where they're going to be stored.
#+begin_src nix
  { wallpapers, ... }:

  {
    # Wallpaper theme
    wallpaper.theme = "name-of-theme";

    # Wallpaper directory location
    wallpaper.directory = "path/to/dir";
  }
#+end_src
